export const EVENT = {
  name: "FinanceExpo Global",
  subtitle: "The Global Expo of Trading and Financial Markets",
  tagline: "Trading · Mercados · Innovación financiera",
  hashtags: "#FinanceExpoGlobal #FinanceExpo2025 #TradingSummit",
  date: "29 — 30 AGOSTO, 2025",
  venue: "Museo de Arte de Lima",
  venueDetail: "Centro de Lima, Perú",
  logo: import.meta.env.BASE_URL + "assets/financeexpo-logo.png",
  logoWhite: import.meta.env.BASE_URL + "assets/financeexpo-logo-white.png",
  isotipo: import.meta.env.BASE_URL + "assets/financeexpo-isotipo.png",
  platformName: "FinanceExpo",
  defaultRole: "ATTENDEE",
  shareText: `🚀 ¡Nos vemos en #FinanceExpoGlobal 2025, la mayor expo de trading y mercados financieros del año.\n\n🔴 Dos días intensos con los principales actores del trading global, paneles, networking y oportunidades para entender el ruido del mercado y convertirlo en decisiones accionables.\n\n*Si vas a asistir, ¡avísame para coincidir!*\n📅 29 – 30 de Agosto, 2025\n📍 Museo de Arte de Lima — Centro de Lima, Perú\n\n#FinanceExpoGlobal #TradingSummit #FinancialMarkets #Networking`,
  eventUrl: "https://finsummit.com",
  // Google Apps Script Web App URL para registro en Google Sheets
  sheetWebhook: "https://script.google.com/macros/s/AKfycbyLZ6EnjTID7vt-QoVcWHp45x-PI6lTet1oxXVPMaRj262PT2R3qOH9WaKB5rJkXLgfCQ/exec",
  theme: {
    seaGreen: "#00644E",
    springGreen: "#00DF82",
    aquamarine: "#58DDA8",
    midnight: "#0B3750",
    greenYellow: "#97E402",
  },
}
