export const EVENT = {
  name: "Finance Expo Argentina",
  subtitle: "#1 Trading, Crypto & Fintech Expo in LATAM & Caribbean",
  tagline: "Trading · Crypto · Fintech",
  hashtags: "#FinanceExpoArgentina #FinanceExpo2026 #TradingExpo",
  date: "23 DE MAYO, 2026",
  dateShort: "23 MAY",
  dateLabel: "Main Day",
  year: "2026",
  venue: "Buenos Aires",
  venueDetail: "Argentina",
  logo: import.meta.env.BASE_URL + "assets/financeexpo-logo.png",
  logoWhite: import.meta.env.BASE_URL + "assets/financeexpo-logo-white.png",
  isotipo: import.meta.env.BASE_URL + "assets/financeexpo-isotipo.png",
  platformName: "FinanceExpo",
  defaultRole: "ATTENDEE",
  shareText: `🚀 ¡Nos vemos en #FinanceExpoArgentina 2026, la #1 expo de Trading, Crypto & Fintech en LATAM & Caribbean.\n\n🔴 Main Day con los principales actores del trading, cripto y fintech, paneles, networking y oportunidades para descifrar el mercado y convertirlo en decisiones accionables.\n\n*Si vas a asistir, ¡avísame para coincidir!*\n📅 23 de Mayo, 2026 — Main Day\n📍 Buenos Aires, Argentina\n\n#FinanceExpoArgentina #TradingExpo #Crypto #Fintech #Networking`,
  eventUrl: "https://financeexpoglobal.com/",
  // Google Apps Script Web App URL para registro en Google Sheets
  sheetWebhook: "https://script.google.com/macros/s/AKfycbyLZ6EnjTID7vt-QoVcWHp45x-PI6lTet1oxXVPMaRj262PT2R3qOH9WaKB5rJkXLgfCQ/exec",
  theme: {
    seaGreen: "#00644E",
    springGreen: "#00DF82",
    aquamarine: "#58DDA8",
    midnight: "#0B3750",
    greenYellow: "#97E402",
  },
}
